name: Dockerize Node.js App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm i -D semantic-release
    #- run: npm run
    #- run: npm i -g jest-cli
    #- run: npm test
    - name: Get smart tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: docker.pkg.github.com/jchima/container-ci-demo
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        push: true
        tags: ${{ steps.prepare.outputs.tag }}
